const products = [
    {
      id: 1,
      name: "Gaming Accessories",
      category: "Gaming",
      image: "URL_OF_IMAGE",
      price: 99.99,
      countInStock: 10,
      description: "High-quality gaming accessories.",
    },
    {
      id: 2,
      name: "Gaming PC",
      category: "Gaming",
      image: "URL_OF_IMAGE",
      price: 1200.0,
      countInStock: 5,
      description: "RGB gaming PC with high performance.",
    },
    {
      id: 3,
      name: "Office Supplies",
      category: "Stationery",
      image: "URL_OF_IMAGE",
      price: 49.99,
      countInStock: 15,
      description: "Complete office stationery set.",
    },
    {
      id: 4,
      name: "Home Storage",
      category: "Home Essentials",
      image: "URL_OF_IMAGE",
      price: 30.0,
      countInStock: 20,
      description: "Elegant storage solutions for your home.",
    },
    {
      id: 5,
      name: "Fashion",
      category: "Fashion",
      image: "URL_OF_IMAGE",
      price: 100,
      countInStock: 10,
      description: "High-quality clothes.",
    },
    {
      id: 6,
      name: "Kitchen Accessories",
      category: "Kitchen",
      image: "URL_OF_IMAGE",
      price: 1200.0,
      countInStock: 5,
      description: "Standard quality kitchen products.",
    },
    {
      id: 7,
      name: "Home Arrivals",
      category: "Home Essentials",
      image: "URL_OF_IMAGE",
      price: 49.99,
      countInStock: 15,
      description: "Complete home needs.",
    },
    {
      id: 8,
      name: "Wireless Technology",
      category: "Wireless Tech",
      image: "URL_OF_IMAGE",
      price: 3000.0,
      countInStock: 20,
      description: "Stay ahead in the modern world.",
    },
  ];
  
  export default products;
  